DROP DATABASE IF EXISTS "quiz";

DROP ROLE IF EXISTS "quiz";

CREATE ROLE "quiz" LOGIN
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE
  PASSWORD 'pofig';

CREATE DATABASE "quiz"
WITH OWNER = "quiz"
ENCODING = 'UTF8'
TABLESPACE = pg_default;

